"""MCP (Model Context Protocol) module for MyCode."""

from .client import (
    MCPClient,
    MCPClient,
    MCPServerConfig,
    MCPTool,
    MCPResource,
    MCPPrompt,
    MCPTransportType,
    HTTPTransport,
    StdioTransport,
    WebSocketTransport,
    get_mcp_client,
    mcp_add,
    mcp_remove,
    mcp_list,
    mcp_connect,
    mcp_disconnect,
    mcp_tools,
    mcp_resources,
    mcp_prompts,
)

__all__ = [
    "MCPClient",
    "MCPServerConfig",
    "MCPTool",
    "MCPResource",
    "MCPPrompt",
    "MCPTransportType",
    "HTTPTransport",
    "StdioTransport",
    "WebSocketTransport",
    "get_mcp_client",
    "mcp_add",
    "mcp_remove",
    "mcp_list",
    "mcp_connect",
    "mcp_disconnect",
    "mcp_tools",
    "mcp_resources",
    "mcp_prompts",
]